# Generated by Django 3.2.3 on 2021-05-30 23:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210530_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa568f47-fefa-40a0-b071-fecb9ecadd78'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.UUID('26daf352-1774-4034-8e4c-771db863983c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
